name: Dependency Security Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Dependencies for Vulnerabilities
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
