name: GitHub Hosted Runners

on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Print OS
        run: echo "Operating System: $RUNNER_OS"

      - name: Print Hostname
        run: hostname

      - name: Print Current User
        run: whoami

  windows:
    runs-on: windows-latest

    steps:
      - name: Print OS
        run: echo "Operating System: $env:RUNNER_OS"

      - name: Print Hostname
        run: hostname

      - name: Print Current User
        run: whoami

  macos:
    runs-on: macos-latest

    steps:
      - name: Print OS
        run: echo "Operating System: $RUNNER_OS"

      - name: Print Hostname
        run: hostname

      - name: Print Current User
        run: whoami
