name: GitHub Hosted Runners

on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print Runner Information
        run: |
          echo "Operating System: $RUNNER_OS"
          hostname
          whoami


      - name: Show Docker Version
        run: docker --version

      - name: Show Python Version
        run: python --version

      - name: Show Node Version
        run: node --version

      - name: Show Git Version
        run: git --version

  windows:
    runs-on: windows-latest
    steps:
      - name: Print Runner Information
        shell: pwsh
        run: |
          Write-Host "Operating System: $env:RUNNER_OS"
          hostname
          whoami

  macos:
    runs-on: macos-latest
    steps:
      - name: Print Runner Information
        run: |
          echo "Operating System: $RUNNER_OS"
          hostname
          whoami
