name: Scheduled Tasks

on:
  schedule:
    - cron: '30 2 * * 1'
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scheduled-health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Show Trigger
        run: |
          echo "Workflow triggered by:"
          echo "${{ github.event.schedule }}"

      - name: Health Check
        run: |
          echo "Checking GitHub..."
          STATUS=$(curl -L -s -o /dev/null -w "%{http_code}" https://github.com)

          echo "HTTP Status Code: $STATUS"

          if [ "$STATUS" -eq 200 ]; then
            echo "Health check passed!"
          else
            echo "Health check failed!"
            exit 1
          fi
