name: Secrets Demo

on:
  workflow_dispatch:

jobs:
  secrets-test:
    runs-on: self-hosted

    steps:
      - name: Test Secret
        run: |
          echo "Secret is working"
          echo "Secret length is ${#MY_SECRET}"

        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
