name: Secrets as Environment Variables

on:
  push:

jobs:
  secrets-env:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret as Environment Variable
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "Secret is available as an environment variable."
          else
            echo "Secret is missing."
          fi

      - name: Check Docker Username
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          if [ -n "$DOCKER_USERNAME" ]; then
            echo "Docker username secret is configured."
          else
            echo "Docker username secret is not configured."
          fi
