name: GitHub Secrets

on:
  push:

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: Try Printing Secret
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"
